
extensions = """
4ops.terraform
charliermarsh.ruff
github.copilot
github.copilot-chat
golang.go
hediet.debug-visualizer
hediet.vscode-drawio
humao.rest-client
mindaro-dev.file-downloader
ms-azuretools.vscode-azureresourcegroups
ms-azuretools.vscode-azurevirtualmachines
ms-azuretools.vscode-cosmosdb
ms-dotnettools.csdevkit
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-kubernetes-tools.vscode-kubernetes-tools
ms-playwright.playwright
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-ai-remote
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.azure-account
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vscode.remote-server
pomdtr.excalidraw-editor
redhat.vscode-yaml
redis.redis-for-vscode
ritwickdey.liveserver
rust-lang.rust-analyzer
scala-lang.scala
simonsiefke.svg-preview
tintinweb.graphviz-interactive-preview
vadimcn.vscode-lldb
vscjava.vscode-java-debug
vscodevim.vim
"""

themes = """
arcticicestudio.nord-visual-studio-code
fabiospampinato.vscode-monokai-night
nimda.deepdark-material
solarliner.linux-themes
"""