# -----------------------------------------------------------------------------
# TOOLS INITIALIZATIONS - MUST BE IN THE END
# -----------------------------------------------------------------------------
eval "$(starship init zsh)"


if [ -f ~/.customrc ]; then
    . ~/.customrc
fi
